name = "NMEAParser"
uuid = "e33883a1-8aa8-4e6e-a42d-0daf9e203b40"
authors = ["Nicholas Shindler <nick@shindler.tech>"]
version = "2.3.0"

[weakdeps]
PrecompileTools = "aea7be01-6a6a-4083-8856-8a6e6704d82a"

[extensions]
PrecompileExt = "PrecompileTools"

[compat]
Aqua = "0.8"
julia = "1.8"

[extras]
Aqua = "4c88cf16-eb10-579e-8560-4a9242c79595"
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Aqua", "Test"]
